---
apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containerscontainers:
spec:
  containers:
    - image: gcr.io/mimetic-radio-405219/demo:v1.0.0
      name: app
      ports:
        - containerPort: 8000
          name: http

    - image: nginx
      name: nginx
      volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
